/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author RodolfoECM
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        EstilosPanel = new javax.swing.JPanel();
        NegritasCheckBox = new javax.swing.JCheckBox();
        CursivasCheckBox = new javax.swing.JCheckBox();
        TamañosPanel = new javax.swing.JPanel();
        pequeño = new javax.swing.JRadioButton();
        mediano = new javax.swing.JRadioButton();
        grande = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cab Martinez");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EstilosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESTILO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        EstilosPanel.setOpaque(false);

        NegritasCheckBox.setSelected(true);
        NegritasCheckBox.setText("Negritas");
        NegritasCheckBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CursivasCheckBox.setText("Cursivas");
        CursivasCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursivasCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EstilosPanelLayout = new javax.swing.GroupLayout(EstilosPanel);
        EstilosPanel.setLayout(EstilosPanelLayout);
        EstilosPanelLayout.setHorizontalGroup(
            EstilosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstilosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EstilosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CursivasCheckBox)
                    .addComponent(NegritasCheckBox))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        EstilosPanelLayout.setVerticalGroup(
            EstilosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstilosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NegritasCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CursivasCheckBox)
                .addGap(30, 30, 30))
        );

        getContentPane().add(EstilosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 142, -1, 130));

        TamañosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TAMAÑO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        TamañosPanel.setOpaque(false);

        grupo.add(pequeño);
        pequeño.setForeground(new java.awt.Color(255, 255, 255));
        pequeño.setSelected(true);
        pequeño.setText("PEQUEÑO");
        pequeño.setOpaque(false);

        grupo.add(mediano);
        mediano.setForeground(new java.awt.Color(255, 255, 255));
        mediano.setText("MEDIANO");
        mediano.setOpaque(false);

        grupo.add(grande);
        grande.setForeground(new java.awt.Color(255, 255, 255));
        grande.setText("GRANDE");
        grande.setOpaque(false);

        javax.swing.GroupLayout TamañosPanelLayout = new javax.swing.GroupLayout(TamañosPanel);
        TamañosPanel.setLayout(TamañosPanelLayout);
        TamañosPanelLayout.setHorizontalGroup(
            TamañosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TamañosPanelLayout.createSequentialGroup()
                .addGroup(TamañosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pequeño)
                    .addComponent(mediano)
                    .addComponent(grande))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        TamañosPanelLayout.setVerticalGroup(
            TamañosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TamañosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pequeño)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mediano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grande)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        TamañosPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {grande, mediano, pequeño});

        getContentPane().add(TamañosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FUENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arial", "Times New Roman", "Calibri", "Verdana", "Tahoma", "Consolas" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 142, -1, 130));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jTextField1.setEditable(false);
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("INSTITUTO TECNOLOGICO DEL ESTADO DE CAMPECHE");
        jTextField1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 21, 356, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/cab.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CursivasCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursivasCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CursivasCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CursivasCheckBox;
    private javax.swing.JPanel EstilosPanel;
    private javax.swing.JCheckBox NegritasCheckBox;
    private javax.swing.JPanel TamañosPanel;
    private javax.swing.JRadioButton grande;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton mediano;
    private javax.swing.JRadioButton pequeño;
    // End of variables declaration//GEN-END:variables
}
